version: '3.8'

volumes:
  db-volume:
  db-es:
    driver: local





#x-frontend: &frontend
#  build:
#    context: .
#    dockerfile: _docker/frontend/Dockerfile
#  image: frontend
#  container_name: "frontend"
#  volumes:
#    - ./frontend:/frontend
#    - /frontend/node_modules

services:
  config_db_verdaccio:
    build:
      context: .
      dockerfile: _docker/verdaccio/Dockerfile
    command: node index.js
    volumes:
      - "./verdaccio:/verdaccio"

  verdaccio:
    image: verdaccio/verdaccio
    container_name: "verdaccio"
    depends_on:
      config_db_verdaccio:
          condition: service_completed_successfully
    restart: unless-stopped
    environment:
      - VERDACCIO_PORT=4873
    ports:
      - "4873:4873"
    volumes:
      - "./verdaccio/storage:/verdaccio/storage"
      - "./verdaccio/conf:/verdaccio/conf"
      - "./verdaccio/plugins:/verdaccio/plugins"
#  frontend:
#    <<: *frontend
#    command: npm run build

